version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 10
    reviewers:
      - "robinmiau"
    assignees:
      - "robinmiau"
    commit-message:
      prefix: "chore"
      include: "scope"
    ignore:
      - dependency-name: "@types/vscode"
        versions: ["*"]
    groups:
      development-dependencies:
        dependency-type: "development"
        patterns:
          - "@types/*"
          - "@typescript-eslint/*"
          - "eslint*"
          - "typescript"
          - "webpack*"
          - "ts-loader"
      ruffle-updates:
        patterns:
          - "@ruffle-rs/*"
